name: "👷 Contribution and submitting new plugins"
description: I have an issue or feature request around submitting new plugins or contributing in general.
body:
  - type: dropdown
    id: location
    attributes:
      label: What does it concern?
      options:
        - The plugin SDK, design, or schema
        - The Makefile commands and tooling
        - The contribution process as a whole
        - Other
    validations:
      required: true
  - type: textarea
    id: desired
    attributes:
      label: Goal or desired behavior
      description: What are you trying to achieve with the SDK, schema, contribution process, etc. that's currently not working well?
    validations:
      required: true
  - type: textarea
    id: current
    attributes:
      label: Current behavior
      description: What does the status quo look like? Why is that bad? Any workarounds worth mentioning?
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: If this is a bug, add any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: input
    id: cli-version
    attributes:
      label: op CLI version
      description: "If relevant, add the output of: op --version"
  - type: input
    id: repo-ref
    attributes:
      label: shell-plugins local ref
      description: "If relevant, add the output of: git show-ref -s refs/heads/main"
